In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [13]:
tumor_data = pd.read_csv("tumor_data.csv")
tumor_np = tumor_data.to_numpy()
tumor_np

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, 8.581e+02, 8.455e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, 1.265e+03, 1.178e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, 1.810e+02, 5.263e-02]],
      shape=(569, 5))

In [14]:
# Find mean of all parameters
mean_values = np.mean(tumor_np, axis=0)
print("Mean of all parameters:", mean_values)

Mean of all parameters: [1.41272917e+01 1.92896485e+01 9.19690334e+01 6.54889104e+02
 9.63602812e-02]


In [17]:
mean_radius = mean_values[0]  
large_tumors = tumor_np[tumor_np[:, 0] > mean_radius]
print("Tumors greater than mean radius:", large_tumors)

Tumors greater than mean radius: [[1.799e+01 1.038e+01 1.228e+02 1.001e+03 1.184e-01]
 [2.057e+01 1.777e+01 1.329e+02 1.326e+03 8.474e-02]
 [1.969e+01 2.125e+01 1.300e+02 1.203e+03 1.096e-01]
 ...
 [2.013e+01 2.825e+01 1.312e+02 1.261e+03 9.780e-02]
 [1.660e+01 2.808e+01 1.083e+02 8.581e+02 8.455e-02]
 [2.060e+01 2.933e+01 1.401e+02 1.265e+03 1.178e-01]]


In [18]:
wine_data=pd.read_excel("wine_data.xlsx")
wine_data

Alcohol  Malic Acid   Ash  Alcalinity of Ash  Magnesium  Total Phenols  \
0      14.23        1.71  2.43               15.6        127           2.80   
1      13.20        1.78  2.14               11.2        100           2.65   
2      13.16        2.36  2.67               18.6        101           2.80   
3      14.37        1.95  2.50               16.8        113           3.85   
4      13.24        2.59  2.87               21.0        118           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5         95           1.68   
174    13.40        3.91  2.48               23.0        102           1.80   
175    13.27        4.28  2.26               20.0        120           1.59   
176    13.17        2.59  2.37               20.0        120           1.65   
177    14.13        4.10  2.74               24.5         96           2.05   

     Flavanoids  Nonflavanoid Phenols  Proanthocyanins   Colour Intensity  \
0          3.06                  0.28             2.29               5.64   
1          2.76                  0.26             1.28               4.38   
2          3.24                  0.30             2.81               5.68   
3          3.49                  0.24             2.18               7.80   
4          2.69                  0.39             1.82               4.32   
..          ...                   ...              ...                ...   
173        0.61                  0.52             1.06               7.70   
174        0.75                  0.43             1.41               7.30   
175        0.69                  0.43             1.35              10.20   
176        0.68                  0.53             1.46               9.30   
177        0.76                  0.56             1.35               9.20   

      Hue  diluted wines  Proline  
0    1.04           3.92     1065  
1    1.05           3.40     1050  
2    1.03           3.17     1185  
3    0.86           3.45     1480  
4    1.04           2.93      735  
..    ...            ...      ...  
173  0.64           1.74      740  
174  0.70           1.56      750  
175  0.59           1.56      835  
176  0.60           1.62      840  
177  0.61           1.60      560  

[178 rows x 13 columns]

In [21]:
wine_data.describe()

Alcohol  Malic Acid         Ash  Alcalinity of Ash   Magnesium  \
count  178.000000  178.000000  178.000000         178.000000  178.000000   
mean    13.000618    2.336348    2.366517          19.494944   99.741573   
std      0.811827    1.117146    0.274344           3.339564   14.282484   
min     11.030000    0.740000    1.360000          10.600000   70.000000   
25%     12.362500    1.602500    2.210000          17.200000   88.000000   
50%     13.050000    1.865000    2.360000          19.500000   98.000000   
75%     13.677500    3.082500    2.557500          21.500000  107.000000   
max     14.830000    5.800000    3.230000          30.000000  162.000000   

       Total Phenols  Flavanoids  Nonflavanoid Phenols  Proanthocyanins  \
count     178.000000  178.000000            178.000000       178.000000   
mean        2.295112    2.029270              0.361854         1.590899   
std         0.625851    0.998859              0.124453         0.572359   
min         0.980000    0.340000              0.130000         0.410000   
25%         1.742500    1.205000              0.270000         1.250000   
50%         2.355000    2.135000              0.340000         1.555000   
75%         2.800000    2.875000              0.437500         1.950000   
max         3.880000    5.080000              0.660000         3.580000   

        Colour Intensity         Hue  diluted wines      Proline  
count         178.000000  178.000000     178.000000   178.000000  
mean            5.058090    0.957449       2.611685   746.893258  
std             2.318286    0.228572       0.709990   314.907474  
min             1.280000    0.480000       1.270000   278.000000  
25%             3.220000    0.782500       1.937500   500.500000  
50%             4.690000    0.965000       2.780000   673.500000  
75%             6.200000    1.120000       3.170000   985.000000  
max            13.000000    1.710000       4.000000  1680.000000

In [24]:
high_alcohol_low_magnesium = wine_data[(wine_data["Alcohol"] > 13.00) & (wine_data["Magnesium"] < 99.74)]
high_alcohol_low_magnesium.head()

Alcohol  Malic Acid   Ash  Alcalinity of Ash  Magnesium  Total Phenols  \
6     14.39        1.87  2.45               14.6         96           2.50   
8     14.83        1.64  2.17               14.0         97           2.80   
9     13.86        1.35  2.27               16.0         98           2.98   
11    14.12        1.48  2.32               16.8         95           2.20   
12    13.75        1.73  2.41               16.0         89           2.60   

    Flavanoids  Nonflavanoid Phenols  Proanthocyanins   Colour Intensity  \
6         2.52                  0.30             1.98               5.25   
8         2.98                  0.29             1.98               5.20   
9         3.15                  0.22             1.85               7.22   
11        2.43                  0.26             1.57               5.00   
12        2.76                  0.29             1.81               5.60   

     Hue  diluted wines  Proline  
6   1.02           3.58     1290  
8   1.08           2.85     1045  
9   1.01           3.55     1045  
11  1.17           2.82     1280  
12  1.15           2.90     1320

In [27]:
hue_min = wine_data["Hue"].min()
hue_max = wine_data["Hue"].max()
hue_range=hue_max-hue_min
print(f"Range of Hue: {hue_range} ")

Range of Hue: 1.23 


In [31]:
correlation = wine_data['Alcohol'].corr(wine_data[' Colour Intensity'])
if abs(correlation) < 0.2:
    print("No significant correlation, displaying odd ones:")
    print(wine_data[(wine_data['Alcohol'] - wine_data['Alcohol'].mean()).abs() > 2 * wine_data['Alcohol'].std()])
else:
    print("There is a correlation between Alcohol and Color Intensity:", correlation)

There is a correlation between Alcohol and Color Intensity: 0.5463641950837038


In [35]:
# Load Share Data
share_df = pd.read_csv('Share_data.csv')

# Mean, Median, Mode
mean_open = share_df['Opening Price'].mean()
median_open = share_df['Opening Price'].median()
mode_open = share_df['Opening Price'].mode()[0]

mean_close = share_df['Closing Price'].mean()
median_close = share_df['Closing Price'].median()
mode_close = share_df['Closing Price'].mode()[0]

print(f"Mean, Median, Mode of Opening Prices: {mean_open}, {median_open}, {mode_open}")
print(f"Mean, Median, Mode of Closing Prices: {mean_close}, {median_close}, {mode_close}")

# Standard Deviation
std_open = share_df['Opening Price'].std()
std_close = share_df['Closing Price'].std()
print(f"Standard deviation of Opening Prices: {std_open}")
print(f"Standard deviation of Closing Prices: {std_close}")

# RMSE with respect to best fit line (assumed as mean value)
rmse_open = np.sqrt(((share_df['Opening Price'] - mean_open) ** 2).mean())
rmse_close = np.sqrt(((share_df['Closing Price'] - mean_close) ** 2).mean())
print(f"RMSE for Opening Prices: {rmse_open}")
print(f"RMSE for Closing Prices: {rmse_close}")


Mean, Median, Mode of Opening Prices: 13.95, 14.0, 10
Mean, Median, Mode of Closing Prices: 14.85, 15.0, 14
Standard deviation of Opening Prices: 2.910507280798134
Standard deviation of Closing Prices: 2.942877217246665
RMSE for Opening Prices: 2.8368115905008566
RMSE for Closing Prices: 2.8683619018526936


In [36]:
x=share_df['Opening Price']
y=share_df['Closing Price']
best_fit=np.polyfit(x,y,1)
pridicated_values=np.polyval(best_fit,x)
rmse=np.sqrt(np.mean((y-pridicated_values)**2))
rmse

np.float64(1.6057329723146305)

In [38]:
emp=pd.read_excel('Emp_info (1).xlsx')
emp.head()

id    city        dept  age   salary  performance score
0  A001  Mumbai       sales   23  1800000                1.4
1  A002   Delhi  technology   35  2500000                7.0
2  A003   Delhi  production   22  1000000                3.8
3  A004  Indore       sales   34  2200000                2.5
4  A005  Mumbai  technology   31   800000                9.0

In [39]:
data=sns.get_dataset_names()
data


['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [41]:
df=sns.load_dataset('titanic')
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]